- name: Elastic-Ansible | Install Playbook
  hosts: "{{hosts}}"
  tasks:
  - name: Install Generic Software
    become: yes
    yum:
      name: nmap
      state: present

  - name: Install Java
    become: yes
    yum:
      name: java-1.8.0-openjdk
      state: present
    when:
    - "'logstash' in sw"
    - "version < '7.10'"

  - name: Install Elastic Stack
    become: yes
    yum:
      name: https://artifacts.elastic.co/downloads/{% if 'beat' in item %}beats/{% else %}{% endif %}{{item}}/{{item}}-{{version}}{% if item == 'logstash' and version <= '7.10' %}{% else %}-x86_64{% endif %}.rpm
      state: present
    loop:
    - elasticsearch
    - kibana
    - logstash
    - filebeat
    - metricbeat
    when: item in sw

  - name: Production Settings - Directory
    become: yes
    file:
      path: /etc/systemd/system/{{item}}.service.d/
      state: directory
    loop:
    - elasticsearch
    - logstash
    when: item in sw

  - name: Production Settings - File
    become: yes
    copy:
      dest: /etc/systemd/system/{{item}}.service.d/override.conf
      content: |
        [Service]
        LimitMEMLOCK=infinity
        AmbientCapabilities=CAP_NET_BIND_SERVICE
    loop:
    - elasticsearch
    - logstash
    when: item in sw
